<?php
// module/Tax/view/tax/payment/index.phtml:

$title = 'Payments';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('payment', ['action' => 'add']) ?>">Add new payment</a>
</p>

<table class="table">
<tr>
    <th>Amount</th>
    <th>Tax</th>
    <th>Tax Rate (%)</th>
    <th>County</th>
    <th>State</th>
    <th>Country</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($payments as $payment) : ?>
    <tr>
        <td><?= $this->escapeHtml($payment->amount) ?></td>
        <td><?= $this->escapeHtml($payment->tax) ?></td>
        <td><?= $this->escapeHtml($payment->tax_rate) ?></td>
        <td><?= $this->escapeHtml($payment->county_name) ?></td>
        <td><?= $this->escapeHtml($payment->state_name) ?></td>
        <td><?= $this->escapeHtml($payment->country_name) ?></td>        
        <td>
            <a href="<?= $this->url('payment', ['action' => 'edit', 'id' => $payment->id]) ?>">Edit</a>
            <a href="<?= $this->url('payment', ['action' => 'delete', 'id' => $payment->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>