<?php
$title = 'Edit Country';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$country = $form->get('name');
$country->setAttribute('class', 'form-control');
$country->setAttribute('placeholder', 'Album title');

$initial = $form->get('initial');
$initial->setAttribute('class', 'form-control');
$initial->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('country', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($country) ?>
    <?= $this->formElement($country) ?>
    <?= $this->formElementErrors()->render($country, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($initial) ?>
    <?= $this->formElement($initial) ?>
    <?= $this->formElementErrors()->render($initial, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();