<?php
$title = 'Edit State';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$state = $form->get('name');
$state->setAttribute('class', 'form-control');
$state->setAttribute('placeholder', 'Name');

$initial = $form->get('initial');
$initial->setAttribute('class', 'form-control');
$initial->setAttribute('placeholder', 'Initial');

// This provides a default CSS class and placeholder text for the country element:
$country = $form->get('country_id');
$country->setAttribute('class', 'form-control');
$country->setAttribute('placeholder', 'Country');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('state', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($state) ?>
    <?= $this->formElement($state) ?>
    <?= $this->formElementErrors()->render($state, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($initial) ?>
    <?= $this->formElement($initial) ?>
    <?= $this->formElementErrors()->render($initial, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($country) ?>
    <?= $this->formElement($country) ?>
    <?= $this->formElementErrors()->render($country, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();